#!/bin/sh /etc/rc.common

START=26
USE_PROCD=1

start_service() {
	/usr/libexec/xg2010g-packet-steering apply-runtime
}

reload_service() {
	/usr/libexec/xg2010g-packet-steering apply-runtime
}

service_triggers() {
	procd_add_reload_trigger network
	# Run after the stock packet_steering interface trigger (1000 ms).
	procd_add_raw_trigger 'interface.*' 1500 /etc/init.d/xg2010g-packet-steering reload
}
